language: python
python:
  - "3.8"
env:
  - DJANGO=4.0
install:
  - pip install -q Django==$DJANGO
  - pip install flake8
  - pip install coveralls
  - pip install -q -e .
before_script:
  - "flake8 tabbed_admin"
script:
  - coverage run --source tabbed_admin tabbed_admin/tests/runtests.py
after_success: coveralls
